ALTER TABLE emails
  ADD COLUMN IF NOT EXISTS summary TEXT,
  ADD COLUMN IF NOT EXISTS priority TEXT,
  ADD COLUMN IF NOT EXISTS priority_score REAL,
  ADD COLUMN IF NOT EXISTS ai_sum_model TEXT,
  ADD COLUMN IF NOT EXISTS ai_cls_model TEXT,
  ADD COLUMN IF NOT EXISTS ai_updated_at TIMESTAMPTZ;
