version: "3.9"

services:
  app:
    ports:
      - "8080:8080"
    environment:
      ENV: development
      LOG_LEVEL: debug

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"