version: "3.9"

name: emailback

networks:
  data: { driver: bridge }

volumes:
  pgdata:

services:
  migrate:
    image: migrate/migrate:4
    depends_on:
      postgres:
        condition: service_healthy
    networks: [data]
    volumes:
      - ../db/migrations:/migrations:ro
    environment:
      DB_USER: ${DB_USER:-emailback}
      DB_PASSWORD: ${DB_PASSWORD:-changeme}
      DB_NAME: ${DB_NAME:-emailback}
    command:
      - "-path"
      - "/migrations"
      - "-database"
      - "postgres://${DB_USER:-emailback}:${DB_PASSWORD:-changeme}@postgres:5432/${DB_NAME:-emailback}?sslmode=disable"
      - "-verbose"
      - "up"
    restart: "no"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-emailback}
      POSTGRES_USER: ${DB_USER:-emailback}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    command: ["redis-server","--save","","--appendonly","no"]
    networks: [data]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: emailback:latest
    env_file:
      - ../.env
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: ${DB_USER:-emailback}
      DB_PASSWORD: ${DB_PASSWORD:-changeme}
      DB_NAME: ${DB_NAME:-emailback}
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_DB: ${REDIS_DB:-0}
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks: [data]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 10s